"""Add crm_task model

Revision ID: 09364ff51dc3
Revises: 23f21a42704f
Create Date: 2025-05-09 11:36:52.672736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09364ff51dc3'
down_revision = '23f21a42704f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('crm_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['crm_account_id'], ['crm_account.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_tasks')
    # ### end Alembic commands ###
