"""Add crm_deal model

Revision ID: 18f32e35a8b7
Revises: 09364ff51dc3
Create Date: 2025-05-10 18:22:48.364899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f32e35a8b7'
down_revision = '09364ff51dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('crm_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['crm_account_id'], ['crm_account.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_deal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_deal_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_deal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_deal_name'))

    op.drop_table('crm_deal')
    # ### end Alembic commands ###
