"""Add CRM models and update CallLog

Revision ID: 23f21a42704f
Revises: 37fb0f8a3547
Create Date: 2025-05-08 12:10:56.944448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23f21a42704f'
down_revision = '37fb0f8a3547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_account_sales_rep_id'), ['sales_rep_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_account_status'), ['status'], unique=False)

    op.create_table('crm_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('crm_account_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crm_account_id'], ['crm_account.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_contact_crm_account_id'), ['crm_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contact_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contact_sales_rep_id'), ['sales_rep_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contact_status'), ['status'], unique=False)

    op.create_table('crm_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('crm_account_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['crm_account_id'], ['crm_account.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_note_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_note_crm_account_id'), ['crm_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_note_sales_rep_id'), ['sales_rep_id'], unique=False)

    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_call_logs_contact_id'), ['contact_id'], unique=False)
        batch_op.create_foreign_key(None, 'crm_contact', ['contact_id'], ['id'])

    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_transaction_activity_type'), ['activity_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transaction_activity_type'))

    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_call_logs_contact_id'))
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('crm_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_note_sales_rep_id'))
        batch_op.drop_index(batch_op.f('ix_crm_note_crm_account_id'))
        batch_op.drop_index(batch_op.f('ix_crm_note_contact_id'))

    op.drop_table('crm_note')
    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_contact_status'))
        batch_op.drop_index(batch_op.f('ix_crm_contact_sales_rep_id'))
        batch_op.drop_index(batch_op.f('ix_crm_contact_email'))
        batch_op.drop_index(batch_op.f('ix_crm_contact_crm_account_id'))

    op.drop_table('crm_contact')
    with op.batch_alter_table('crm_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_account_status'))
        batch_op.drop_index(batch_op.f('ix_crm_account_sales_rep_id'))

    op.drop_table('crm_account')
    # ### end Alembic commands ###
