"""Add SalesUser model and link CallLog

Revision ID: 37fb0f8a3547
Revises: 0452a91c2e0b
Create Date: 2025-05-05 14:44:21.373435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fb0f8a3547'
down_revision = '0452a91c2e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extension'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_rep_id', sa.Integer(), nullable=True))
        batch_op.alter_column('operator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_call_logs_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_sales_rep_id'), ['sales_rep_id'], unique=False)
        batch_op.create_foreign_key(None, 'sales_user', ['sales_rep_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_call_logs_sales_rep_id'))
        batch_op.drop_index(batch_op.f('ix_call_logs_operator_id'))
        batch_op.alter_column('operator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('sales_rep_id')

    op.drop_table('sales_user')
    # ### end Alembic commands ###
