"""Add notes relationship to Deal and Task

Revision ID: 508fb803b4b7
Revises: ccdaaa0cf224
Create Date: 2025-05-12 10:04:39.038944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508fb803b4b7'
down_revision = 'ccdaaa0cf224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_crm_note_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_note_task_id'), ['task_id'], unique=False)
        batch_op.create_foreign_key(None, 'crm_deal', ['deal_id'], ['id'])
        batch_op.create_foreign_key(None, 'crm_tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_crm_note_task_id'))
        batch_op.drop_index(batch_op.f('ix_crm_note_deal_id'))
        batch_op.drop_column('task_id')
        batch_op.drop_column('deal_id')

    # ### end Alembic commands ###
