"""Add start_time and end_time to call_logs

Revision ID: 63779209a82f
Revises: 95a44399a17b
Create Date: 2025-04-08 11:25:05.159317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63779209a82f'
down_revision = '95a44399a17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
