"""Replace custom_data with CustomFieldValue relationship

Revision ID: 6c86008c386a
Revises: f68078cad54c
Create Date: 2025-05-12 17:31:50.858005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c86008c386a'
down_revision = 'f68078cad54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_account', schema=None) as batch_op:
        batch_op.drop_column('custom_data')

    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.drop_column('custom_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('crm_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
