"""add_safety_configuration_fields_fixed

Revision ID: 81e6da7527cd
Revises: 3556b6dbbcad
Create Date: 2025-03-10 11:11:26.883636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e6da7527cd'
down_revision = '3556b6dbbcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth',
    sa.Column('provider_user_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_user_id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_per_truck', sa.Float(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'new'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
        batch_op.drop_column('price_per_truck')
        batch_op.drop_column('truck_count')

    op.drop_table('oauth')
    # ### end Alembic commands ###
