"""Add is_admin and unique_link fields to User model

Revision ID: 8cb2e19ff930
Revises: 131e47e19d46
Create Date: 2025-02-04 15:47:13.201810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb2e19ff930'
down_revision = '131e47e19d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('unique_link', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_unique_link', ['unique_link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_unique_link', type_='unique')
        batch_op.drop_column('unique_link')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
