"""Add company_id to samsara_client

Revision ID: 941d3e955202
Revises: 4161ae5d2291
Create Date: 2025-05-23 11:19:23.510131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941d3e955202'
down_revision = '4161ae5d2291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samsara_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samsara_clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
