"""Add geographic and device data columns to link_click

Revision ID: 998f882e71ee
Revises: 28a6a5b841dc
Create Date: 2025-02-04 17:02:05.760071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998f882e71ee'
down_revision = '28a6a5b841dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_click', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_click', schema=None) as batch_op:
        batch_op.drop_column('device_type')
        batch_op.drop_column('region')
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
