"""Add service status fields to Company model

Revision ID: add_service_status_fields
Revises: 948b19bed1c0
Create Date: 2024-03-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_service_status_fields'
down_revision = '948b19bed1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safety_status', sa.String(length=20), nullable=True, server_default='inactive'))
        batch_op.add_column(sa.Column('recruitment_status', sa.String(length=20), nullable=True, server_default='inactive'))
        batch_op.add_column(sa.Column('recruitment_requests', postgresql.JSONB(), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('recruitment_requests')
        batch_op.drop_column('recruitment_status')
        batch_op.drop_column('safety_status') 