"""Add is_primary_for_account to Contact model

Revision ID: b241242f0648
Revises: f787afd58568
Create Date: 2025-05-17 21:07:48.654656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b241242f0648'
down_revision = 'f787afd58568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_primary_for_account', sa.Boolean(), nullable=True))

    # Update existing rows to set a default value for the new column
    op.execute('UPDATE crm_contact SET is_primary_for_account = FALSE WHERE is_primary_for_account IS NULL')

    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.alter_column('is_primary_for_account', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.drop_column('is_primary_for_account')
        batch_op.drop_column('custom_data')

    # ### end Alembic commands ###
