"""Add unique constraint to Contact.email

Revision ID: ccdaaa0cf224
Revises: bcd80c37fcc1
Create Date: 2025-05-10 22:09:14.199755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdaaa0cf224'
down_revision = 'bcd80c37fcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.drop_index('ix_crm_contact_email')
        batch_op.create_index(batch_op.f('ix_crm_contact_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_contact_email'))
        batch_op.create_index('ix_crm_contact_email', ['email'], unique=False)

    # ### end Alembic commands ###
