"""Add serial field to samsara_vehicles

Revision ID: ce7fb773ca5f
Revises: 9adc2d5cc33f
Create Date: 2025-04-15 15:19:40.139950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7fb773ca5f'
down_revision = '9adc2d5cc33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samsara_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samsara_vehicles', schema=None) as batch_op:
        batch_op.drop_column('serial')

    # ### end Alembic commands ###
