"""make_sales_rep_id_nullable_for_contacts_and_accounts

Revision ID: f0fe9eb792ae
Revises: f5966f44b059
Create Date: 2025-05-13 17:16:57.921313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fe9eb792ae'
down_revision = 'f5966f44b059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.alter_column('sales_rep_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('crm_account', schema=None) as batch_op:
        batch_op.alter_column('sales_rep_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_account', schema=None) as batch_op:
        batch_op.alter_column('sales_rep_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('crm_contact', schema=None) as batch_op:
        batch_op.alter_column('sales_rep_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
