"""Add custom field tables

Revision ID: f68078cad54c
Revises: 508fb803b4b7
Create Date: 2025-05-12 17:14:32.033734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68078cad54c'
down_revision = '508fb803b4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'DROPDOWN', 'BOOLEAN', name='customfieldtype'), nullable=False),
    sa.Column('applies_to', sa.Enum('CONTACT', 'ACCOUNT', name='customfieldappliesto'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_applies_to'), ['applies_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_name'), ['name'], unique=False)

    op.create_table('custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['crm_account.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['definition_id'], ['custom_field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_values_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_definition_id'), ['definition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_field_values_definition_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_contact_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_account_id'))

    op.drop_table('custom_field_values')
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_applies_to'))

    op.drop_table('custom_field_definitions')
    # ### end Alembic commands ###
