"""Add dot_number field to CrmAccount

Revision ID: f787afd58568
Revises: f0fe9eb792ae
Create Date: 2025-05-15 11:41:35.435819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f787afd58568'
down_revision = 'f0fe9eb792ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dot_number', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_crm_account_dot_number'), ['dot_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_account_dot_number'))
        batch_op.drop_column('dot_number')

    # ### end Alembic commands ###
